Feature portfolio
Sammy3000/my-portfolio pull request #1
Opened 2022-11-30 22:20 UTC by Sammy3000

## In this pull request I did the following:
- I added the navigation bar.
- I added the first content section which had the greetings and the paragraph lines.
- customized my readme file to include my social profilings.

2022-11-30 23:10 UTC, emmiiorji requested changes
Hi @Sammy3000, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project that the readme documentation is not properly customized. Kindly remove the descriptions given by the template.
![image](https://user-images.githubusercontent.com/20554583/204927299-eeee129a-3a2a-4ae1-899a-40942b25f800.png)

Also, kindly ensure that the link to MIT file is not a broken one and that the note below the license is removed as it is only an instruction to the author of the repo. 
![image](https://user-images.githubusercontent.com/20554583/204927396-27d90db4-38e5-497c-b2dc-faaeb7214feb.png)

An appropriate title is also needed for the project. Kindly adjust this too.
![image](https://user-images.githubusercontent.com/20554583/204928173-120ec620-715b-41a1-aca8-70154da0f20e.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-01 07:24 UTC, Felix45 requested changes
Hi @Sammy3000 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights :heavy_check_mark: 
- [ ] All linter checks are setup and passing :white_check_mark: 
- [ ] Good descriptive pull request summary :white_check_mark: 
- [ ] Good descriptive commit messages :white_check_mark: 
- [ ] Github flow is correctly used :white_check_mark: 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-01 07:24 UTC, Felix45 commented on style.css
> +}
- [ Required ] Good job adding a background image to this `section` element, however on large screens it's not responsive. To make it responsive please consider giving it a `background-size: 100%;` to make the image responsive across small and large devices.

2022-12-01 07:24 UTC, Felix45 commented on index.html
> +      />
- [ Required ] Please consider adding a `ul` list with `li`'s that contain links `a` tag to the following social media pages twitter, linkedin, medium, github and angelist. In the coming months you'll use these social media pages for networking and job search so please add them.
### Example code
```HTML
<ul>
  <li><a href="http://twitter.com/yourhandle/"><img src="twitter_logo.png" /></a></li>
  <li><a href="http://linkedin.com/yourprofile/"><img src="linkedin_logo.png" /></a></li>
  <li><a href="http://facebook.com/yourprofile/"><img src="facebook_logo.png" /></a></li>
 <li><a href="http://medium.com/yourprofile/"><img src="medium_logo.png" /></a></li>
</ul>
```

2022-12-01 07:24 UTC, Felix45 commented on README.md
> -This project is [MIT](./LICENSE) licensed.
[ required ]  On the readme file the link to the project LICENSE is very important in a project that has to do with intellectual property such as this one, please add a file named LICENSE to the project and make sure its contents are those of the [MIT License](https://choosealicense.com/licenses/mit/) on this [link](https://choosealicense.com/licenses/mit/). Remember to customize the `year` and `fullname` fields of the License and finally add the following lines to your `readme` file.

### Example markdown
```
## 📝 License <a name="license"></a>

This project is [MIT](./LICENSE) licensed.
````

2022-12-01 08:02 UTC, Sammy3000 commented on index.html
> +    </nav>
@Felix45 noted.

2022-12-01 08:46 UTC, Sammy3000 commented on index.html
> +      />
@Felix45 I thought the social media icons should not link anywhere for now.

2022-12-01 09:23 UTC, Sammy3000 commented on README.md
> -This project is [MIT](./LICENSE) licensed.
Thank you.

2022-12-01 09:57 UTC, Felix45 commented on index.html
> +      />
@Sammy3000 you should at the least have a Twitter, GitHub, Facebook and LinkedIn account

2022-12-01 10:00 UTC, Sammy3000 commented on index.html
> +      />
@Felix45  okay noted thanks.

2022-12-01 10:01 UTC, merged