Feature portfolio
Sammy3000/my-portfolio pull request #2
Opened 2022-12-01 23:25 UTC by Sammy3000

## In this project I did the following.
- Created the about section .
- I styled the about section with appropriate images and layout.

2022-12-02 01:13 UTC, brainconnect93 requested changes
### Hi @Sammy3000, 👋 

# STATUS: Changes Required :recycle:

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/kghYzGafFW0AAAAM/almost-paul-walker.gif">

### To Highlight :1st_place_medal: 
-  Has a proper Pull Request. ✔️  
- No Linter errors :heavy_check_mark: 
- Good use of Github flow ✔️ 

### Changes Required

- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 01:13 UTC, brainconnect93 commented on index.html
> +              src="Images/icons8-linkedin-2-32.png"
- [ ] I notice from my end all the social media images are not. this might be because the directory name where the images are located is not properly targeted. Kindly check this out and fix it.

Here is what I have 👇

![med](https://user-images.githubusercontent.com/78634841/205190394-f88a5418-c8f3-4a79-b41b-e728a14b7d53.png)

2022-12-02 01:13 UTC, brainconnect93 commented on index.html
> +          <img src="Images/Ellipse 1 (1).png" alt="javascript logo" />
- [ ] I would suggest you kindly fix the link of the images, as the languages i.e `JavaScript`, `HTML`, and `CSS` images are broken from my end here

- Here is what I have 👇

![lang](https://user-images.githubusercontent.com/78634841/205190904-22a3d2e7-09e5-446c-a291-1e47ad1b7873.png)

2022-12-02 01:13 UTC, brainconnect93 commented on style.css
> +}
- [ ] I would kindly suggest you give your `See Project` as well as the `Get my resume` button some `Active`, `Hover`, and `Pressed` styling as shown in the[ Figma template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1&t=FKBvXOXX9rZtBa1A-0)

Kindly check out this for your peruse: 👇 

![btn](https://user-images.githubusercontent.com/78634841/205191872-51eebf0a-e1ce-44ca-91f9-6fd526b0f046.png)

2022-12-02 18:24 UTC, anagudelogu requested changes
# STATUS: CHANGES REQUIRED ♻️ 🚧 

Hi @Sammy3000 👋🏼 
I'm Andres.

You've done a great job implementing some of the requested changes for this milestone 🚀, but there are still some which haven't been addressed yet. You're getting closer, keep up the good work! 🤖 🎆 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

 ## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Great UI design. 💻 
✅ Descriptive PR title, summary and commit messages. 💬 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 18:24 UTC, anagudelogu commented on index.html
> +      </div>
- [ ] As the previous reviewer requested, It would be better if you can use an `<ul>` for this part of your portfolio. This is because you're listing skills: Languages, Frameworks, and Skills.

Please consider refactoring your code to end up with something like this:

```HTML
<ul>
  <li>
    <h3> Languages </h3>
    <ul>
      <li> JavaScript </li>
      <li> HTML </li>
      <li> CSS </li>
    </ul>
  <li>
  <li>
    <h3> Frameworks </h3>
  <li>
  <li>
    <h3> Skills </h3>
  <li>
</ul>

```

Please consider implementing this change! 🤓 🛠️

2022-12-03 06:57 UTC, bienvenuushindi approved these changes
# STATUS: APPROVED 🟢 

## Hi @Sammy3000   👋, 

Well done implementing the requested changes 👏
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/lJNoBCvQYp7nq/giphy.gif"/>

### Highlights 🎯 
:+1: No linter errors✔️
:+1: Good UI design✔️
:+1: Good PR title

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 12:20 UTC, merged