Feature desktop
Sammy3000/my-portfolio pull request #4
Opened 2022-12-08 19:59 UTC by Sammy3000

## In this repository branch I did the following:
- I created a desktop version of our mobile portfolio using media query.
- Created another branch which I used to create a pull request.

2022-12-08 21:00 UTC, binhussen requested changes
Hi @Sammy3000 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights

- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️

## Required Changes ♻️
- Kindly, stick to the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1&t=9yEMN2Ie0jK1Zj4x-0) as match as possible. 👌👍

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-08 21:00 UTC, binhussen commented on style.css
> +  }
- Kindly, your header navigation needs some padding to stick to the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1&t=9yEMN2Ie0jK1Zj4x-0) .👌👍


| Your design                                                             | Figma design                                         |
| --------------------------------------------------------------------------------| --------------------------------------------------------- |
|<img src="https://user-images.githubusercontent.com/52010789/206562583-fdf3b7dd-8133-4ff4-8f14-1aecf53427cd.png" width="200">|<img src="https://user-images.githubusercontent.com/52010789/206562597-83b308ec-0329-4284-89e8-2fa8b8480749.png" width="200">|


😎️

2022-12-08 21:00 UTC, binhussen commented on style.css
> +  }
- Kindly, use some background images as the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1&t=9yEMN2Ie0jK1Zj4x-0)👌👍


| Your design                                                             | Figma design                                         |
| --------------------------------------------------------------------------------| --------------------------------------------------------- |
|<img src="https://user-images.githubusercontent.com/52010789/206563289-c68a886d-d6c5-4a78-847c-55648dbf8422.png" width="200">|<img src="https://user-images.githubusercontent.com/52010789/206563300-008cca56-f272-4cf5-9eb9-46a26832b07e.png" width="200">|


😎️

2022-12-08 21:00 UTC, binhussen commented on style.css
> +  }
- Kindly, stick your list down arrow as [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1&t=9yEMN2Ie0jK1Zj4x-0)👌👍


| Your design                                                             | Figma design                                         |
| --------------------------------------------------------------------------------| --------------------------------------------------------- |
|<img src="https://user-images.githubusercontent.com/52010789/206565604-a46024ae-74c3-46c3-8098-7d3cf741ff1c.png" width="200">|<img src="https://user-images.githubusercontent.com/52010789/206565610-bc8ee045-6aaf-405e-8c9b-c633b06a3809.png" width="200">|


😎️

2022-12-08 21:30 UTC, binhussen commented
@Sammy3000, there was some issue while doing the review on your PR, it's being solved right now. In the meantime you can work on the requested changes, please don't submit the PR on your dashboard until the issue is solved. 😔😔

2022-12-09 06:50 UTC, Sammy3000 commented on style.css
> +  }
- Thanks for the review @binhussen .Everything fixed but my dashboard has an issue. Hopefully it gets fixed soon since the week is almost over.

2022-12-09 09:09 UTC, enniopo commented
Hi @Sammy3000 you can request another code review request now. Please go ahead and sorry for the inconvenience.

2022-12-09 21:20 UTC, merged